import { Message as MessageType } from "@shared/schema";
import { cn } from "@/lib/utils";
import { FileText, Image as ImageIcon } from "lucide-react";

interface MessageProps {
  message: MessageType;
}

export default function Message({ message }: MessageProps) {
  const isUser = message.role === "user";
  const files = message.files as any[] || [];

  return (
    <div className={cn("flex", isUser ? "justify-end" : "justify-start")}>
      <div className={cn(
        "max-w-3xl px-4 py-3 rounded-xl",
        isUser 
          ? "bg-purple-primary text-white" 
          : "bg-dark-secondary border border-gray-700 text-white"
      )}>
        {/* Files */}
        {files.length > 0 && (
          <div className="mb-3 space-y-2">
            {files.map((file, index) => (
              <div key={index}>
                {file.type?.startsWith('image/') ? (
                  <div className="border border-gray-600 rounded-lg p-2">
                    <img 
                      src={file.preview || file.data} 
                      alt={file.name}
                      className="max-w-48 h-auto rounded-lg"
                    />
                    <p className="text-xs text-gray-300 mt-1">{file.name}</p>
                  </div>
                ) : (
                  <div className="flex items-center space-x-2 border border-gray-600 rounded-lg p-2">
                    <FileText className="w-4 h-4 text-red-400" />
                    <span className="text-sm">{file.name}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Text content */}
        {message.content && (
          <div className="whitespace-pre-wrap">{message.content}</div>
        )}

        {/* Model info for assistant messages */}
        {!isUser && message.model && (
          <div className="text-xs text-muted mt-2 opacity-75">
            Generated by {message.model}
          </div>
        )}
      </div>
    </div>
  );
}
